### ISSUE TITLE
Out-dated FSF address

### ISSUE THREAD

**Issue by ppisar** [rurban/re-engine-PCRE2#22]
The LICENSE file quotes Free Software Foundation's postal address that is not valid anymore. Current one can be found at <https://www.gnu.org/licenses/old-licenses/gpl-1.0.txt>. Please update the license wording to provide up-to-date address to your users.

**Comment by rurban** [comment]
@avar Objections to switch from GPL 1.0 + Artistic 1.0 to GPL 2.0 + Artistic 1.0?

**Comment by avar** [comment]
You can license my meagre contributions however you like.

However in this case I think there's a good practical argument to licensing
it exactly like perl itself, once this module in complete integrating it an
a build option to perl itself would be a no brainer

**Comment by rurban** [comment]
Ok. GPL1 then. The FSF will not like that.

Interestingly I looked up the wording via google and there you get
https://dev.perl.org/licenses/gpl1.html
still with the old address.
