### ISSUE TITLE
Compile error with perl 5.34

### ISSUE THREAD

**Issue by todd-richmond** [rurban/re-engine-PCRE2#38]
PCRE2.xs no longer compiles because perl 5.34 #ifndefs out quite a few header declarations when PERL_EXT_RE_BUILD is not defined. Simple fix

*** PCRE2.xs.org	2021-08-25 21:51:37.991220377 -0700
--- PCRE2.xs	2021-08-25 21:51:54.080355417 -0700
***************
*** 1,4 ****
--- 1,5 ----
  /* -*- c-basic-offset:4 -*- */
+ #define PERL_EXT_RE_BUILD
  #include "EXTERN.h"
  #include "perl.h"
  #include "XSUB.h"

**Comment by rurban** [comment]
There is no perl 8.34.
There is an old discontinued pcre1 8.34, which was replaced by pcre2
We wont support the old pcre.

**Comment by todd-richmond** [comment]
typo - i meant perl 5.34. Latest perl with latest pcre2 10.37

**Comment by todd-richmond** [comment]
fixed in commit ad0f3b9
